# Generated by Django 6.1 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("users_list_view", "Can view users list")]},
        ),
    ]
