# Generated by Django 6.1 on 2026-08-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0003_service_is_active_alter_service_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Channel")),
            ],
        ),
        migrations.CreateModel(
            name="AdCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Budget"
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                        verbose_name="Connection",
                    ),
                ),
                (
                    "channel",
                    models.ManyToManyField(
                        to="ad_companies.channel", verbose_name="Channel"
                    ),
                ),
            ],
        ),
    ]
