# Generated by Django 6.1 on 2026-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=20, unique=True, verbose_name="Channel"),
        ),
    ]
