# Generated by Django 6.1 on 2026-08-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_companies", "0002_alter_channel_name"),
        ("services", "0003_service_is_active_alter_service_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adcompany",
            options={
                "verbose_name": "Ad Company",
                "verbose_name_plural": "Ad Companies",
            },
        ),
        migrations.AddField(
            model_name="adcompany",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="adcompany",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connection",
                to="services.service",
                verbose_name="Connection",
            ),
        ),
    ]
