# Generated by Django 6.1 on 2026-08-18 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_companies", "0003_alter_adcompany_options_adcompany_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adcompany",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="data creating",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adcompany",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="adcompany",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="data modifying"),
        ),
        migrations.AddField(
            model_name="adcompany",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
    ]
