# Generated by Django 6.1 on 2026-08-19 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad_companies", "0004_adcompany_created_at_adcompany_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcompany",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Budget",
            ),
        ),
    ]
