# Generated by Django 6.1 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ad_companies", "0005_alter_adcompany_budget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adcompany",
            options={
                "permissions": [("view_ads_list", "Can view ads list")],
                "verbose_name": "Ad Company",
                "verbose_name_plural": "Ad Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={"permissions": [("view_channels_list", "Can view channels list")]},
        ),
    ]
