# Generated by Django 6.1 on 2026-08-18 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import contracts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0003_service_is_active_alter_service_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Name")),
                ("start_date", models.DateField(verbose_name="start")),
                ("finish_date", models.DateField(verbose_name="finish")),
                (
                    "agreed_finish_date",
                    models.DateField(blank=True, null=True, verbose_name="Agreed date"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Cost"
                    ),
                ),
                (
                    "agreed_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Agreed cost"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=contracts.models.create_contract_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_modifier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
        ),
    ]
