# Generated by Django 6.1 on 2026-08-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="close"),
        ),
        migrations.AlterField(
            model_name="contract",
            name="agreed_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Agreed cost",
            ),
        ),
    ]
