# Generated by Django 6.1 on 2026-08-19 08:04

import django.db.models.deletion
from django.db import migrations, models

import contracts.models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_is_finished_alter_contract_agreed_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraFilesToContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to=contracts.models.uploadextrafiles,
                        verbose_name="extra files",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_files",
                        to="contracts.contract",
                        verbose_name="Contract name",
                    ),
                ),
            ],
        ),
    ]
