# Generated by Django 6.1 on 2026-08-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_extrafilestocontract"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="service",
            new_name="connection",
        ),
    ]
