# Generated by Django 6.1 on 2026-08-19 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_rename_service_contract_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="agreed_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Agreed cost",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Cost",
            ),
        ),
    ]
