# Generated by Django 6.1 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_alter_contract_agreed_cost_alter_contract_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={
                "permissions": [
                    ("close_contract", "Can close contract"),
                    ("view_contracts_list", "Can view contracts list"),
                ]
            },
        ),
    ]
