# Generated by Django 6.1 on 2026-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Name"),
        ),
    ]
