# Generated by Django 6.1 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"permissions": [("services_list_view", "Can view services list")]},
        ),
    ]
