# Generated by Django 6.1 on 2026-09-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activeclient",
            options={
                "permissions": [("view_all_clients_list", "can view all clients list")]
            },
        ),
        migrations.AlterModelOptions(
            name="potentialclient",
            options={"permissions": [("view_clients_list", "Can view clients list")]},
        ),
    ]
