"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
from os import getenv

load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
secret_key=getenv("secret_key")
SECRET_KEY = secret_key

if secret_key is None:
    raise ValueError("You need your secret key in .env")

# SECURITY WARNING: don't run with debug turned on in production!
debug_param=getenv("debug", 0)
debug=False
if debug_param =="1":
    debug=True
DEBUG = debug

allowed_hosts_from_env=getenv("extra_allowed_hosts", "").split(",")
extra_hosts=[h.strip() for h in allowed_hosts_from_env if h.strip()]
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
] + extra_hosts

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users",
    "user_auth",
    "services",
    "ad_companies",
    "clients",
    "contracts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/"templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "common_files.check_perms.links_and_buttons",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

database_path=BASE_DIR/"database"
Path(database_path).mkdir(exist_ok=True)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": database_path / "db.sqlite3",
    },
    "postgresql": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": getenv("dbname", "crm_db"),
        "USER": getenv("user", "crm_user"),
        "HOST": getenv("host", "localhost"),
        "PORT": getenv("port", "5432"),
        "PASSWORD": getenv("password", "123456")


    }
}

database_name=getenv("database", "default")

DATABASES={"default":DATABASES[database_name]}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
static_dir=getenv("static_dir", "static")
STATIC_URL = "static/"
static_dir=BASE_DIR/static_dir
Path(static_dir).mkdir(exist_ok=True)
STATICFILES_DIRS = static_dir,

STATIC_ROOT=BASE_DIR/"staticfiles"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


LOGIN_URL="auth:login"
login_redirect=getenv("login_redirect", "auth:main")
LOGIN_REDIRECT_URL=login_redirect

logout_redirect=getenv("logout_redirect", "auth:main")
LOGOUT_REDIRECT_URL=logout_redirect

AUTH_USER_MODEL="users.User"

MEDIA_URL="media/"

media_dir=getenv("media_dir", "media")
media_path=BASE_DIR/media_dir
Path(media_path).mkdir(exist_ok=True)
MEDIA_ROOT=media_path


